using System.Collections;

public enum ItemID : ushort {
	GRASSBLOCK,
	DIRTBLOCK,
	STONEBLOCK,
	WOODBLOCK,
	METALBLOCK,
	WATERBLOCK,
	TORCH,
	LEAFBLOCK,
	SANDBLOCK,
	SNOWBLOCK,
	ICEBLOCK,
    BASALTBLOCK,
    CLAYBLOCK,
    STONEBRICKBLOCK,
    WOODENPLANKSREGULARBLOCK,
    WOODENPLANKSPINEBLOCK,
    BONEBLOCK,
    SANDSTONEBRICKBLOCK,
    SANDSTONEBLOCK
}
