public enum BoneAnchorType: byte {
	BASE_CHARACTER_BELT_CURVED_RIGHT,
	BASE_CHARACTER_BELT_CURVED_LEFT,
	BASE_CHARACTER_BELT_STRAIGHT_RIGHT,
	BASE_CHARACTER_BELT_STRAIGHT_LEFT,
	BASE_CHARACTER_BACK_CURVED_RIGHT,
	BASE_CHARACTER_BACK_CURVED_LEFT,
	BASE_CHARACTER_BACK_STRAIGHT,
	BASE_CHARACTER_BACK_SHIELD,
	BASE_CHARACTER_HAND_RIGHT,
	BASE_CHARACTER_HAND_LEFT
}