//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Controls/InventoryUIControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InventoryUIControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InventoryUIControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InventoryUIControls"",
    ""maps"": [
        {
            ""name"": ""InventoryUI"",
            ""id"": ""7d7f9582-556a-4890-a459-bc6657de0b3b"",
            ""actions"": [
                {
                    ""name"": ""Drop"",
                    ""type"": ""Button"",
                    ""id"": ""27fbe102-c660-4a5d-9bc0-9c19b6ee0479"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ebfcb914-1222-494e-8b17-c92ae1405b71"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // InventoryUI
        m_InventoryUI = asset.FindActionMap("InventoryUI", throwIfNotFound: true);
        m_InventoryUI_Drop = m_InventoryUI.FindAction("Drop", throwIfNotFound: true);
    }

    ~@InventoryUIControls()
    {
        UnityEngine.Debug.Assert(!m_InventoryUI.enabled, "This will cause a leak and performance issues, InventoryUIControls.InventoryUI.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // InventoryUI
    private readonly InputActionMap m_InventoryUI;
    private List<IInventoryUIActions> m_InventoryUIActionsCallbackInterfaces = new List<IInventoryUIActions>();
    private readonly InputAction m_InventoryUI_Drop;
    public struct InventoryUIActions
    {
        private @InventoryUIControls m_Wrapper;
        public InventoryUIActions(@InventoryUIControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Drop => m_Wrapper.m_InventoryUI_Drop;
        public InputActionMap Get() { return m_Wrapper.m_InventoryUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InventoryUIActions set) { return set.Get(); }
        public void AddCallbacks(IInventoryUIActions instance)
        {
            if (instance == null || m_Wrapper.m_InventoryUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InventoryUIActionsCallbackInterfaces.Add(instance);
            @Drop.started += instance.OnDrop;
            @Drop.performed += instance.OnDrop;
            @Drop.canceled += instance.OnDrop;
        }

        private void UnregisterCallbacks(IInventoryUIActions instance)
        {
            @Drop.started -= instance.OnDrop;
            @Drop.performed -= instance.OnDrop;
            @Drop.canceled -= instance.OnDrop;
        }

        public void RemoveCallbacks(IInventoryUIActions instance)
        {
            if (m_Wrapper.m_InventoryUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInventoryUIActions instance)
        {
            foreach (var item in m_Wrapper.m_InventoryUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InventoryUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InventoryUIActions @InventoryUI => new InventoryUIActions(this);
    public interface IInventoryUIActions
    {
        void OnDrop(InputAction.CallbackContext context);
    }
}
