public enum AttributeName : byte{
	STRENGTH,
	PRECISION,
	VITALITY,
	EVASION,
	MAGIC,
	CHARISMA,
	FIRE_RESISTANCE,
	ICE_RESISTANCE,
	LIGHTNING_RESISTANCE,
	POISON_RESISTANCE,
	CURSE_RESISTANCE,
	SPEED
}